const RouteName = {
    SPLASH_SCREEN: 'SPLASH_SCREEN',
    WELCOME_SCREEN: 'WELCOME_SCREEN',
    NAME_SCREEN: 'NAME_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN',
    LIKED_IDEA_SCREEN: 'LIKED_IDEA_SCREEN',
    MORE_SCREEN: 'MORE_SCREEN',
    QUOTE_SCREEN: 'QUOTE_SCREEN',
}

export default RouteName;