const BusinessIdeas = [
    // Tech Services
    {
      title: "Custom Software Development",
      category: "Tech Services",
      description: "Offer custom software development solutions to businesses in need of specialized software applications.",
      image: "https://via.placeholder.com/300x200.png?text=Custom+Software",
    },
    {
      title: "Mobile App Development",
      category: "Tech Services",
      description: "Develop mobile applications for Android and iOS platforms tailored to client requirements.",
      image: "https://via.placeholder.com/300x200.png?text=Mobile+App",
    },
    {
      title: "Web Design and Development",
      category: "Tech Services",
      description: "Create modern and responsive websites for businesses and individuals.",
      image: "https://via.placeholder.com/300x200.png?text=Web+Design",
    },
    {
      title: "IT Consulting Services",
      category: "Tech Services",
      description: "Provide IT consulting services to help businesses improve their technology infrastructure.",
      image: "https://via.placeholder.com/300x200.png?text=IT+Consulting",
    },
    {
      title: "Cybersecurity Solutions",
      category: "Tech Services",
      description: "Offer cybersecurity services to protect businesses from online threats and attacks.",
      image: "https://via.placeholder.com/300x200.png?text=Cybersecurity",
    },
    {
      title: "E-commerce Store Setup",
      category: "Tech Services",
      description: "Help businesses set up and optimize their e-commerce stores for online sales.",
      image: "https://via.placeholder.com/300x200.png?text=E-commerce",
    },
    {
      title: "Graphic Design Services",
      category: "Tech Services",
      description: "Provide graphic design services for branding, marketing materials, and more.",
      image: "https://via.placeholder.com/300x200.png?text=Graphic+Design",
    },
    {
      title: "Cloud Computing Solutions",
      category: "Tech Services",
      description: "Assist businesses in migrating to and managing cloud-based infrastructure.",
      image: "https://via.placeholder.com/300x200.png?text=Cloud+Computing",
    },
    {
      title: "Data Analytics Consulting",
      category: "Tech Services",
      description: "Offer data analytics and insights to help businesses make informed decisions.",
      image: "https://via.placeholder.com/300x200.png?text=Data+Analytics",
    },
    {
      title: "Social Media Management",
      category: "Tech Services",
      description: "Manage and grow businesses' social media presence to engage with customers.",
      image: "https://via.placeholder.com/300x200.png?text=Social+Media",
    },
    // Online Retail
    {
      title: "Fashion E-Store",
      category: "Online Retail",
      description: "Start an online fashion store selling clothing, accessories, and footwear.",
      image: "https://via.placeholder.com/300x200.png?text=Fashion+E-Store",
    },
    {
      title: "Electronics Online Shop",
      category: "Online Retail",
      description: "Sell electronic gadgets, appliances, and accessories through an online platform.",
      image: "https://via.placeholder.com/300x200.png?text=Electronics+Store",
    },
    {
      title: "Books and Media Marketplace",
      category: "Online Retail",
      description: "Create an online marketplace for books, movies, music, and collectibles.",
      image: "https://via.placeholder.com/300x200.png?text=Books+Marketplace",
    },
    {
      title: "Health and Wellness Products",
      category: "Online Retail",
      description: "Sell health supplements, fitness equipment, and wellness products online.",
      image: "https://via.placeholder.com/300x200.png?text=Wellness+Products",
    },
    {
      title: "Home Decor and Furnishings",
      category: "Online Retail",
      description: "Offer a wide range of home decor and furnishings for online shoppers.",
      image: "https://via.placeholder.com/300x200.png?text=Home+Decor",
    },
    {
      title: "Pet Supplies Store",
      category: "Online Retail",
      description: "Create an online store for pet food, accessories, and grooming products.",
      image: "https://via.placeholder.com/300x200.png?text=Pet+Supplies",
    },
    {
      title: "Sports and Outdoor Gear",
      category: "Online Retail",
      description: "Sell sports equipment, outdoor gear, and activewear through an online platform.",
      image: "https://via.placeholder.com/300x200.png?text=Sports+Gear",
    },
    {
      title: "Crafts and Handmade Goods",
      category: "Online Retail",
      description: "Feature handmade crafts and artisanal goods in an online store.",
      image: "https://via.placeholder.com/300x200.png?text=Handmade+Crafts",
    },
    {
      title: "Auto Parts and Accessories",
      category: "Online Retail",
      description: "Start an online store offering auto parts, accessories, and tools.",
      image: "https://via.placeholder.com/300x200.png?text=Auto+Parts",
    },
    {
      title: "Gourmet Food Marketplace",
      category: "Online Retail",
      description: "Curate and sell gourmet food products from around the world online.",
      image: "https://via.placeholder.com/300x200.png?text=Gourmet+Food",
    },
    // Food & Bev
    {
      title: "Gourmet Food Truck",
      category: "Food & Bev",
      description: "Start a gourmet food truck offering unique and delicious dishes to customers.",
      image: "https://via.placeholder.com/300x200.png?text=Gourmet+Food+Truck",
    },
    {
      title: "Healthy Meal Delivery",
      category: "Food & Bev",
      description: "Offer healthy meal delivery services with customizable menu options.",
      image: "https://via.placeholder.com/300x200.png?text=Healthy+Meal+Delivery",
    },
    {
      title: "Coffee Shop and Cafe",
      category: "Food & Bev",
      description: "Open a cozy coffee shop and cafe serving specialty coffee and baked goods.",
      image: "https://via.placeholder.com/300x200.png?text=Coffee+Shop",
    },
    {
      title: "Craft Brewery",
      category: "Food & Bev",
      description: "Brew and sell craft beer with unique flavors and brewpub experience.",
      image: "https://via.placeholder.com/300x200.png?text=Craft+Brewery",
    },
    {
      title: "Food Catering Services",
      category: "Food & Bev",
      description: "Provide catering services for weddings, events, and corporate functions.",
      image: "https://via.placeholder.com/300x200.png?text=Catering+Services",
    },
    {
      title: "Vegetarian and Vegan Restaurant",
      category: "Food & Bev",
      description: "Open a restaurant specializing in vegetarian and vegan cuisine.",
      image: "https://via.placeholder.com/300x200.png?text=Vegan+Restaurant",
    },
    {
      title: "Bakery and Pastry Shop",
      category: "Food & Bev",
      description: "Start a bakery offering a variety of fresh pastries, bread, and cakes.",
      image: "https://via.placeholder.com/300x200.png?text=Bakery",
    },
    {
      title: "Wine Bar and Lounge",
      category: "Food & Bev",
      description: "Create a wine bar and lounge featuring a curated selection of wines.",
      image: "https://via.placeholder.com/300x200.png?text=Wine+Bar",
    },
    {
      title: "Food Truck Park",
      category: "Food & Bev",
      description: "Establish a food truck park with a variety of culinary offerings in one location.",
      image: "https://via.placeholder.com/300x200.png?text=Food+Truck+Park",
    },
    {
      title: "Ice Cream Parlor",
      category: "Food & Bev",
      description: "Open an ice cream parlor serving a wide range of ice cream flavors and treats.",
      image: "https://via.placeholder.com/300x200.png?text=Ice+Cream+Parlor",
    },
    // Wellness
    {
      title: "Yoga Studio",
      category: "Wellness",
      description: "Open a yoga studio where people can practice yoga and improve their well-being.",
      image: "https://via.placeholder.com/300x200.png?text=Yoga+Studio",
    },
    {
      title: "Meditation Retreats",
      category: "Wellness",
      description: "Organize meditation retreats for individuals seeking relaxation and mindfulness.",
      image: "https://via.placeholder.com/300x200.png?text=Meditation+Retreats",
    },
    {
      title: "Spa and Wellness Center",
      category: "Wellness",
      description: "Offer spa treatments, massages, and wellness programs to promote relaxation.",
      image: "https://via.placeholder.com/300x200.png?text=Spa+Wellness",
    },
    {
      title: "Fitness Coaching",
      category: "Wellness",
      description: "Provide personal fitness coaching and training services to help clients achieve their goals.",
      image: "https://via.placeholder.com/300x200.png?text=Fitness+Coaching",
    },
    {
      title: "Nutrition Consulting",
      category: "Wellness",
      description: "Offer nutrition consulting services to help individuals make healthier dietary choices.",
      image: "https://via.placeholder.com/300x200.png?text=Nutrition+Consulting",
    },
    {
      title: "Holistic Healing Center",
      category: "Wellness",
      description: "Establish a holistic healing center offering alternative therapies and treatments.",
      image: "https://via.placeholder.com/300x200.png?text=Holistic+Healing",
    },
    {
      title: "Mindfulness Workshops",
      category: "Wellness",
      description: "Conduct mindfulness workshops and courses to improve mental well-being.",
      image: "https://via.placeholder.com/300x200.png?text=Mindfulness+Workshops",
    },
    {
      title: "Fitness Equipment Retail",
      category: "Wellness",
      description: "Sell fitness equipment, supplements, and activewear through a retail store.",
      image: "https://via.placeholder.com/300x200.png?text=Fitness+Retail",
    },
    {
      title: "Health and Wellness Blog",
      category: "Wellness",
      description: "Create a blog focused on health and wellness topics, attracting a global audience.",
      image: "https://via.placeholder.com/300x200.png?text=Wellness+Blog",
    },
    {
      title: "Senior Care Services",
      category: "Wellness",
      description: "Offer senior care and support services to improve the quality of life for elderly individuals.",
      image: "https://via.placeholder.com/300x200.png?text=Senior+Care",
    },
    // Real Estate
    {
      title: "Real Estate Agency",
      category: "Real Estate",
      description: "Start a real estate agency helping clients buy, sell, or rent properties.",
      image: "https://via.placeholder.com/300x200.png?text=Real+Estate+Agency",
    },
    {
      title: "Property Management",
      category: "Real Estate",
      description: "Offer property management services for property owners and landlords.",
      image: "https://via.placeholder.com/300x200.png?text=Property+Management",
    },
    {
      title: "Home Renovation Services",
      category: "Real Estate",
      description: "Provide home renovation and remodeling services to homeowners.",
      image: "https://via.placeholder.com/300x200.png?text=Home+Renovation",
    },
    {
      title: "Real Estate Photography",
      category: "Real Estate",
      description: "Specialize in real estate photography to help market properties effectively.",
      image: "https://via.placeholder.com/300x200.png?text=Real+Estate+Photography",
    },
    {
      title: "Commercial Real Estate Brokerage",
      category: "Real Estate",
      description: "Focus on commercial real estate transactions and leasing services.",
      image: "https://via.placeholder.com/300x200.png?text=Commercial+Real+Estate",
    },
    {
      title: "Home Inspection Services",
      category: "Real Estate",
      description: "Offer home inspection services to homebuyers and sellers for property evaluations.",
      image: "https://via.placeholder.com/300x200.png?text=Home+Inspection",
    },
    {
      title: "Real Estate Investment",
      category: "Real Estate",
      description: "Invest in real estate properties for rental income and capital appreciation.",
      image: "https://via.placeholder.com/300x200.png?text=Investment+Properties",
    },
    {
      title: "Vacation Rental Management",
      category: "Real Estate",
      description: "Manage vacation rental properties on behalf of owners for optimal occupancy.",
      image: "https://via.placeholder.com/300x200.png?text=Vacation+Rental",
    },
    {
      title: "Real Estate Appraisal",
      category: "Real Estate",
      description: "Provide real estate appraisal services to determine property values.",
      image: "https://via.placeholder.com/300x200.png?text=Real+Estate+Appraisal",
    },
    {
      title: "Real Estate Education",
      category: "Real Estate",
      description: "Offer real estate education and training programs for aspiring professionals.",
      image: "https://via.placeholder.com/300x200.png?text=Real+Estate+Education",
    },
    // Education
    {
      title: "Online Tutoring Services",
      category: "Education",
      description: "Provide online tutoring services for students in various subjects.",
      image: "https://via.placeholder.com/300x200.png?text=Online+Tutoring",
    },
    {
      title: "Language Learning Courses",
      category: "Education",
      description: "Offer language learning courses and classes for individuals interested in mastering a new language.",
      image: "https://via.placeholder.com/300x200.png?text=Language+Learning",
    },
    {
      title: "STEM Education Workshops",
      category: "Education",
      description: "Conduct STEM (Science, Technology, Engineering, and Mathematics) education workshops for students.",
      image: "https://via.placeholder.com/300x200.png?text=STEM+Education",
    },
    {
      title: "Music and Arts School",
      category: "Education",
      description: "Establish a music and arts school providing lessons in various creative disciplines.",
      image: "https://via.placeholder.com/300x200.png?text=Music+Arts+School",
    },
    {
      title: "Coding Bootcamp",
      category: "Education",
      description: "Offer coding bootcamps and programming courses to aspiring developers.",
      image: "https://via.placeholder.com/300x200.png?text=Coding+Bootcamp",
    },
    {
      title: "Online Course Marketplace",
      category: "Education",
      description: "Create an online marketplace for courses on various subjects, allowing instructors to sell their expertise.",
      image: "https://via.placeholder.com/300x200.png?text=Online+Course",
    },
    {
      title: "Private School",
      category: "Education",
      description: "Start a private school offering a personalized and quality education experience.",
      image: "https://via.placeholder.com/300x200.png?text=Private+School",
    },
    {
      title: "Educational Toys and Games",
      category: "Education",
      description: "Sell educational toys, games, and learning materials for children.",
      image: "https://via.placeholder.com/300x200.png?text=Educational+Toys",
    },
    {
      title: "Educational Mobile Apps",
      category: "Education",
      description: "Develop mobile apps aimed at helping students learn and improve their skills.",
      image: "https://via.placeholder.com/300x200.png?text=Educational+Apps",
    },
    {
      title: "Study Abroad Consulting",
      category: "Education",
      description: "Assist students in planning and applying for study abroad programs.",
      image: "https://via.placeholder.com/300x200.png?text=Study+Abroad",
    },
    // Home Improvement
    {
      title: "Home Renovation Services",
      category: "Home Improvement",
      description: "Offer home renovation and remodeling services to homeowners.",
      image: "https://via.placeholder.com/300x200.png?text=Home+Renovation",
    },
    {
      title: "Interior Design Consultation",
      category: "Home Improvement",
      description: "Provide interior design consultation and services to transform living spaces.",
      image: "https://via.placeholder.com/300x200.png?text=Interior+Design",
    },
    {
      title: "Landscape Design and Gardening",
      category: "Home Improvement",
      description: "Design and create beautiful outdoor landscapes and gardens for residential properties.",
      image: "https://via.placeholder.com/300x200.png?text=Landscape+Design",
    },
    {
      title: "Handyman Services",
      category: "Home Improvement",
      description: "Offer general handyman services for repairs and maintenance in homes and businesses.",
      image: "https://via.placeholder.com/300x200.png?text=Handyman+Services",
    },
    {
      title: "Roofing and Exterior Repairs",
      category: "Home Improvement",
      description: "Specialize in roofing and exterior repairs to protect properties from the elements.",
      image: "https://via.placeholder.com/300x200.png?text=Roofing+Repairs",
    },
    {
      title: "Appliance Repair Services",
      category: "Home Improvement",
      description: "Provide repair services for household appliances, such as refrigerators and washing machines.",
      image: "https://via.placeholder.com/300x200.png?text=Appliance+Repair",
    },
    {
      title: "Home Security Solutions",
      category: "Home Improvement",
      description: "Install and maintain home security systems to protect families and properties.",
      image: "https://via.placeholder.com/300x200.png?text=Home+Security",
    },
    {
      title: "Carpentry and Woodworking",
      category: "Home Improvement",
      description: "Offer custom carpentry and woodworking services for unique furniture and fixtures.",
      image: "https://via.placeholder.com/300x200.png?text=Carpentry+Services",
    },
    {
      title: "Painting and Wall Art",
      category: "Home Improvement",
      description: "Provide painting and wall art services to transform interior and exterior spaces.",
      image: "https://via.placeholder.com/300x200.png?text=Painting+Services",
    },
    {
      title: "Home Energy Efficiency",
      category: "Home Improvement",
      description: "Help homeowners make their homes more energy-efficient through upgrades and improvements.",
      image: "https://via.placeholder.com/300x200.png?text=Energy+Efficiency",
    },
    // Fashion
    {
      title: "Fashion Boutique",
      category: "Fashion",
      description: "Open a boutique selling trendy clothing, accessories, and fashion items.",
      image: "https://via.placeholder.com/300x200.png?text=Fashion+Boutique",
    },
    {
      title: "Custom Tailoring Services",
      category: "Fashion",
      description: "Offer custom tailoring services for individuals looking for personalized clothing.",
      image: "https://via.placeholder.com/300x200.png?text=Custom+Tailoring",
    },
    {
      title: "Jewelry Design and Sales",
      category: "Fashion",
      description: "Design and sell unique and handmade jewelry pieces.",
      image: "https://via.placeholder.com/300x200.png?text=Jewelry+Design",
    },
    {
      title: "Vintage Clothing Store",
      category: "Fashion",
      description: "Curate and sell vintage and retro clothing items and accessories.",
      image: "https://via.placeholder.com/300x200.png?text=Vintage+Clothing",
    },
    {
      title: "Athletic Apparel Brand",
      category: "Fashion",
      description: "Create and market athletic and sportswear clothing and accessories.",
      image: "https://via.placeholder.com/300x200.png?text=Athletic+Apparel",
    },
    {
      title: "Shoe Boutique",
      category: "Fashion",
      description: "Open a boutique specializing in stylish and comfortable footwear.",
      image: "https://via.placeholder.com/300x200.png?text=Shoe+Boutique",
    },
    {
      title: "Fashion Blogging",
      category: "Fashion",
      description: "Start a fashion blog to share style tips, trends, and outfit inspiration.",
      image: "https://via.placeholder.com/300x200.png?text=Fashion+Blogging",
    },
    {
      title: "Designer Handbags",
      category: "Fashion",
      description: "Design and sell designer handbags and purses with unique styles.",
      image: "https://via.placeholder.com/300x200.png?text=Designer+Handbags",
    },
    {
      title: "Ethical Fashion Brand",
      category: "Fashion",
      description: "Create an ethical fashion brand with sustainable and eco-friendly clothing.",
      image: "https://via.placeholder.com/300x200.png?text=Ethical+Fashion",
    },
    {
      title: "Fashion Illustration Services",
      category: "Fashion",
      description: "Offer fashion illustration and design services for clothing brands and designers.",
      image: "https://via.placeholder.com/300x200.png?text=Fashion+Illustration",
    },
    // Sustainability
    {
      title: "Zero Waste Store",
      category: "Sustainability",
      description: "Open a zero-waste store selling package-free and sustainable products.",
      image: "https://via.placeholder.com/300x200.png?text=Zero+Waste+Store",
    },
    {
      title: "Upcycled Furniture",
      category: "Sustainability",
      description: "Create and sell upcycled furniture and home decor items made from reclaimed materials.",
      image: "https://via.placeholder.com/300x200.png?text=Upcycled+Furniture",
    },
    {
      title: "Eco-Friendly Cleaning Products",
      category: "Sustainability",
      description: "Manufacture and sell eco-friendly and non-toxic cleaning products.",
      image: "https://via.placeholder.com/300x200.png?text=Eco-Friendly+Cleaning",
    },
    {
      title: "Solar Panel Installation",
      category: "Sustainability",
      description: "Offer solar panel installation services to promote clean and renewable energy sources.",
      image: "https://via.placeholder.com/300x200.png?text=Solar+Installation",
    },
    {
      title: "Organic Farming",
      category: "Sustainability",
      description: "Start an organic farm producing pesticide-free fruits, vegetables, and herbs.",
      image: "https://via.placeholder.com/300x200.png?text=Organic+Farming",
    },
    {
      title: "Recycling Collection Service",
      category: "Sustainability",
      description: "Provide recycling collection services for homes and businesses to reduce waste.",
      image: "https://via.placeholder.com/300x200.png?text=Recycling+Service",
    },
    {
      title: "Sustainable Fashion Marketplace",
      category: "Sustainability",
      description: "Create an online marketplace for sustainable and eco-friendly fashion brands.",
      image: "https://via.placeholder.com/300x200.png?text=Sustainable+Fashion",
    },
    {
      title: "Green Building Consulting",
      category: "Sustainability",
      description: "Offer consulting services for green and sustainable building projects.",
      image: "https://via.placeholder.com/300x200.png?text=Green+Building",
    },
    {
      title: "Composting Solutions",
      category: "Sustainability",
      description: "Provide composting solutions and products for reducing food and garden waste.",
      image: "https://via.placeholder.com/300x200.png?text=Composting",
    },
    {
      title: "Environmental Education",
      category: "Sustainability",
      description: "Educate individuals and communities about environmental conservation and sustainability.",
      image: "https://via.placeholder.com/300x200.png?text=Environmental+Education",
    },
    // Entertainment
    {
      title: "Event Planning and Management",
      category: "Entertainment",
      description: "Offer event planning and management services for weddings, parties, and corporate events.",
      image: "https://via.placeholder.com/300x200.png?text=Event+Planning",
    },
    {
      title: "Live Music Venue",
      category: "Entertainment",
      description: "Open a live music venue featuring local and touring artists and bands.",
      image: "https://via.placeholder.com/300x200.png?text=Live+Music+Venue",
    },
    {
      title: "Video Game Development",
      category: "Entertainment",
      description: "Develop and publish video games for various platforms and genres.",
      image: "https://via.placeholder.com/300x200.png?text=Video+Game+Development",
    },
    {
      title: "Escape Room Experience",
      category: "Entertainment",
      description: "Create immersive escape room experiences with challenging puzzles and themes.",
      image: "https://via.placeholder.com/300x200.png?text=Escape+Room",
    },
    {
      title: "Comedy Club",
      category: "Entertainment",
      description: "Establish a comedy club showcasing stand-up comedians and comedy acts.",
      image: "https://via.placeholder.com/300x200.png?text=Comedy+Club",
    },
    {
      title: "Film Production Company",
      category: "Entertainment",
      description: "Start a film production company to create movies, documentaries, and digital content.",
      image: "https://via.placeholder.com/300x200.png?text=Film+Production",
    },
    {
      title: "Indoor Trampoline Park",
      category: "Entertainment",
      description: "Open an indoor trampoline park with various attractions for all ages.",
      image: "https://via.placeholder.com/300x200.png?text=Trampoline+Park",
    },
    {
      title: "Virtual Reality Arcade",
      category: "Entertainment",
      description: "Launch a virtual reality arcade where customers can experience immersive VR games.",
      image: "https://via.placeholder.com/300x200.png?text=VR+Arcade",
    },
    {
      title: "Karaoke Lounge",
      category: "Entertainment",
      description: "Create a karaoke lounge and bar for singing enthusiasts and night-time entertainment.",
      image: "https://via.placeholder.com/300x200.png?text=Karaoke+Lounge",
    },
    {
      title: "Outdoor Movie Theater",
      category: "Entertainment",
      description: "Set up an outdoor movie theater for community screenings and events.",
      image: "https://via.placeholder.com/300x200.png?text=Outdoor+Theater",
    },
  ];
  
  export default BusinessIdeas;
  